# Generated by Django 5.0.6 on 2026-07-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'solar'", unique=True)),
                ('name', models.CharField(max_length=80)),
                ('short', models.CharField(help_text='One-line tagline on cards', max_length=160)),
                ('icon', models.CharField(default='solar', help_text='Icon key: solar, heater, wind, rain, ev, battery, biogas, compost, roof, grey', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('cost', models.CharField(blank=True, max_length=80)),
                ('subsidy', models.CharField(blank=True, max_length=120)),
                ('saving', models.CharField(blank=True, max_length=80)),
                ('payback', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('interest', models.CharField(blank=True, max_length=120)),
                ('property_type', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('tag', models.CharField(help_text='Small label, e.g. Subsidy / Basics', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(help_text='Separate paragraphs with a blank line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_whatsapp', models.CharField(default='919000000000', help_text='Country code + number, digits only. e.g. 919812345678', max_length=20)),
                ('region', models.CharField(default='Delhi NCR', max_length=80)),
                ('listing_price', models.CharField(default='₹100', max_length=20)),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SupplierApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=140)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=25)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('services', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('area', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=25)),
                ('whatsapp', models.CharField(help_text='Country code + number, digits only', max_length=20)),
                ('description', models.TextField()),
                ('since', models.CharField(blank=True, help_text='Year established, e.g. 2019', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='dealers', to='directory.category')),
            ],
            options={
                'ordering': ['-is_verified', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Fixed keys used by the calculators', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='directory.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
